package mixeff4s.comparison

/** Frozen references. Regenerated by comparison/scripts/vendor_harness.py. */
private[comparison] object EmbeddedFrozen:
  val json: String = """{
  "schema": {
    "name": "mixeff4s.frozen_reference",
    "version": 1
  },
  "source": {
    "mixeff_rs_revision": "d6b81ce8b5974b2f0e42fcf650ad6811e5202a4f",
    "lme4_tool": "lme4 2.0.1",
    "note": "Seed pins are the numbers already checked in mixeff4s fit suites. Additional rust and lme4 rows were copied from mixeff-rs comparison artifacts at the recorded revision. No live R or Julia was run. A frozen lme4 row is not a mixeff4s claim until the scorecard says so. There are no p-values."
  },
  "results": [
    {
      "dataset": "sleepstudy",
      "formula": "reaction ~ 1 + days + (1 + days | subj)",
      "family": "Gaussian",
      "link": "Identity",
      "estimator": "ML",
      "engine": "mixedmodels.jl",
      "status": "ok",
      "n_obs": 180,
      "objective": 1751.9393444636682,
      "objective_definition": "deviance",
      "objective_comparable": true,
      "beta": [
        251.40510484848454,
        10.467285959596126
      ],
      "coef_names": [
        "(Intercept)",
        "days"
      ],
      "theta": [
        0.9292297167514472,
        0.01816466496782548,
        0.22264601131030412
      ],
      "sigma": 25.591813564885108,
      "tolerances": {
        "objective": 0.01,
        "beta": 0.001,
        "theta": 0.001,
        "sigma": 0.001
      }
    },
    {
      "dataset": "sleepstudy",
      "formula": "reaction ~ 1 + days + (1 + days | subj)",
      "family": "Gaussian",
      "link": "Identity",
      "estimator": "REML",
      "engine": "mixedmodels.jl",
      "status": "ok",
      "n_obs": 180,
      "objective": 1743.6282719599442,
      "objective_definition": "restricted_deviance",
      "objective_comparable": true,
      "beta": [
        251.40510484848528,
        10.467285959595493
      ],
      "coef_names": [
        "(Intercept)",
        "days"
      ],
      "theta": [
        0.9667417690560796,
        0.015169059384716037,
        0.2309099529619309
      ],
      "sigma": 25.591795732317802,
      "tolerances": {
        "objective": 0.01,
        "beta": 0.001,
        "theta": 0.001,
        "sigma": 0.001
      }
    },
    {
      "dataset": "penicillin",
      "formula": "diameter ~ 1 + (1 | plate) + (1 | sample)",
      "family": "Gaussian",
      "link": "Identity",
      "estimator": "ML",
      "engine": "mixedmodels.jl",
      "status": "ok",
      "n_obs": 144,
      "objective": 332.1883486700085,
      "objective_definition": "deviance",
      "objective_comparable": true,
      "beta": [
        22.97222222222222
      ],
      "coef_names": [
        "(Intercept)"
      ],
      "theta": [
        1.5375939045981573,
        3.219792193110907
      ],
      "tolerances": {
        "objective": 0.01,
        "beta": 0.001,
        "theta": 0.01
      }
    },
    {
      "dataset": "penicillin",
      "formula": "diameter ~ 1 + (1 | plate) + (1 | sample)",
      "family": "Gaussian",
      "link": "Identity",
      "estimator": "REML",
      "engine": "mixeff-rs",
      "status": "ok",
      "n_obs": 144,
      "objective": 330.86058899126897,
      "objective_definition": "restricted_deviance",
      "objective_comparable": true,
      "beta": [
        22.97222222222248
      ],
      "coef_names": [
        "(Intercept)"
      ],
      "theta": [
        1.5396773350745998,
        3.51241122181154
      ],
      "sigma": 0.549923173720829,
      "tolerances": {
        "objective": 0.01,
        "beta": 0.001,
        "theta": 0.01,
        "sigma": 0.001
      }
    },
    {
      "dataset": "pastes",
      "formula": "strength ~ 1 + (1 | batch / cask)",
      "family": "Gaussian",
      "link": "Identity",
      "estimator": "ML",
      "engine": "mixedmodels.jl",
      "status": "ok",
      "n_obs": 60,
      "objective": 247.9944658624955,
      "objective_definition": "deviance",
      "objective_comparable": true,
      "beta": [
        60.0533333333333
      ],
      "coef_names": [
        "(Intercept)"
      ],
      "theta": [
        3.5269029347766856,
        1.3299137410046242
      ],
      "tolerances": {
        "objective": 0.01,
        "beta": 0.001,
        "theta": 0.09
      }
    },
    {
      "dataset": "contraception",
      "formula": "use_num ~ 1 + age + age2 + urban + livch + (1 | urban_dist)",
      "family": "Bernoulli",
      "link": "Logit",
      "estimator": "fast_pirls",
      "engine": "mixedmodels.jl",
      "status": "ok",
      "n_obs": 1934,
      "objective": 2361.657202855648,
      "objective_definition": "profiled_fast_pirls_deviance",
      "objective_comparable": true,
      "theta": [
        0.5720746212924732
      ],
      "sigma": 1.0,
      "tolerances": {
        "objective": 1.0,
        "theta": 0.01
      }
    },
    {
      "dataset": "dyestuff",
      "formula": "Yield ~ 1 + (1 | Batch)",
      "family": "Gaussian",
      "link": "Identity",
      "estimator": "REML",
      "engine": "mixeff-rs",
      "status": "ok",
      "n_obs": 30,
      "objective": 319.65427684225597,
      "objective_definition": "restricted_deviance",
      "objective_comparable": true,
      "beta": [
        1527.4999999999998
      ],
      "coef_names": [
        "(Intercept)"
      ],
      "theta": [
        0.8483243229023545
      ],
      "sigma": 49.5100957160886,
      "is_singular": false
    },
    {
      "dataset": "dyestuff",
      "formula": "Yield ~ 1 + (1 | Batch)",
      "family": "Gaussian",
      "link": "Identity",
      "estimator": "ML",
      "engine": "mixeff-rs",
      "status": "ok",
      "n_obs": 30,
      "objective": 327.327059881646,
      "objective_definition": "deviance",
      "objective_comparable": true,
      "beta": [
        1527.5000000000007
      ],
      "coef_names": [
        "(Intercept)"
      ],
      "theta": [
        0.7525732146822598
      ],
      "sigma": 49.51017269106905,
      "is_singular": false
    },
    {
      "dataset": "dyestuff2",
      "formula": "Yield ~ 1 + (1 | Batch)",
      "family": "Gaussian",
      "link": "Identity",
      "estimator": "ML",
      "engine": "mixeff-rs",
      "status": "ok",
      "n_obs": 30,
      "objective": 162.87303665382575,
      "objective_definition": "deviance",
      "objective_comparable": true,
      "beta": [
        5.665600000000001
      ],
      "coef_names": [
        "(Intercept)"
      ],
      "theta": [
        0.0
      ],
      "sigma": 3.6532313513746506,
      "is_singular": true
    },
    {
      "dataset": "dyestuff2",
      "formula": "Yield ~ 1 + (1 | Batch)",
      "family": "Gaussian",
      "link": "Identity",
      "estimator": "REML",
      "engine": "mixeff-rs",
      "status": "ok",
      "n_obs": 30,
      "objective": 161.82827781228843,
      "objective_definition": "restricted_deviance",
      "objective_comparable": true,
      "beta": [
        5.665600000000001
      ],
      "coef_names": [
        "(Intercept)"
      ],
      "theta": [
        0.0
      ],
      "sigma": 3.7156842744757252,
      "is_singular": true
    },
    {
      "dataset": "pastes",
      "formula": "strength ~ 1 + (1 | sample) + (1 | batch)",
      "family": "Gaussian",
      "link": "Identity",
      "estimator": "REML",
      "engine": "mixeff-rs",
      "status": "ok",
      "n_obs": 60,
      "objective": 246.99074585342348,
      "objective_definition": "restricted_deviance",
      "objective_comparable": true,
      "beta": [
        60.053333333334166
      ],
      "coef_names": [
        "(Intercept)"
      ],
      "theta": [
        3.5269055170508676,
        1.5634659013792063
      ],
      "sigma": 0.8234070274632455,
      "is_singular": false
    },
    {
      "dataset": "penicillin",
      "formula": "diameter ~ 1 + (1 | plate) + (1 | sample)",
      "family": "Gaussian",
      "link": "Identity",
      "estimator": "REML",
      "engine": "mixeff-rs",
      "status": "ok",
      "n_obs": 144,
      "objective": 330.86058899126897,
      "objective_definition": "restricted_deviance",
      "objective_comparable": true,
      "beta": [
        22.97222222222248
      ],
      "coef_names": [
        "(Intercept)"
      ],
      "theta": [
        1.5396773350745998,
        3.51241122181154
      ],
      "sigma": 0.549923173720829,
      "is_singular": false
    },
    {
      "dataset": "sleepstudy",
      "formula": "Reaction ~ 1 + Days + (1 + Days | Subject)",
      "family": "Gaussian",
      "link": "Identity",
      "estimator": "REML",
      "engine": "mixeff-rs",
      "status": "ok",
      "n_obs": 180,
      "objective": 1743.6282719599442,
      "objective_definition": "restricted_deviance",
      "objective_comparable": true,
      "beta": [
        251.40510484848528,
        10.467285959595493
      ],
      "coef_names": [
        "(Intercept)",
        "Days"
      ],
      "theta": [
        0.9667417690560796,
        0.015169059384716037,
        0.2309099529619309
      ],
      "sigma": 25.591795732317802,
      "is_singular": false
    },
    {
      "dataset": "sleepstudy",
      "formula": "Reaction ~ 1 + Days + (1 + Days | Subject)",
      "family": "Gaussian",
      "link": "Identity",
      "estimator": "ML",
      "engine": "mixeff-rs",
      "status": "ok",
      "n_obs": 180,
      "objective": 1751.939344474405,
      "objective_definition": "deviance",
      "objective_comparable": true,
      "beta": [
        251.40510484848537,
        10.4672859595958
      ],
      "coef_names": [
        "(Intercept)",
        "Days"
      ],
      "theta": [
        0.9292145007480422,
        0.018171743703656894,
        0.222646742690827
      ],
      "sigma": 25.591813564885108,
      "is_singular": false
    },
    {
      "dataset": "dyestuff",
      "formula": "Yield ~ 1 + (1 | Batch)",
      "family": "Gaussian",
      "link": "Identity",
      "estimator": "REML",
      "engine": "lme4",
      "status": "ok",
      "n_obs": 30,
      "objective": 319.6543,
      "objective_definition": "restricted_deviance",
      "objective_comparable": true,
      "beta": [
        1527.5
      ],
      "coef_names": [
        "(Intercept)"
      ],
      "theta": [
        0.8483
      ],
      "sigma": 49.5101,
      "is_singular": false
    },
    {
      "dataset": "dyestuff",
      "formula": "Yield ~ 1 + (1 | Batch)",
      "family": "Gaussian",
      "link": "Identity",
      "estimator": "ML",
      "engine": "lme4",
      "status": "ok",
      "n_obs": 30,
      "objective": 327.3271,
      "objective_definition": "deviance",
      "objective_comparable": true,
      "beta": [
        1527.5
      ],
      "coef_names": [
        "(Intercept)"
      ],
      "theta": [
        0.7526
      ],
      "sigma": 49.5101,
      "is_singular": false
    },
    {
      "dataset": "dyestuff2",
      "formula": "Yield ~ 1 + (1 | Batch)",
      "family": "Gaussian",
      "link": "Identity",
      "estimator": "ML",
      "engine": "lme4",
      "status": "ok",
      "n_obs": 30,
      "objective": 162.873,
      "objective_definition": "deviance",
      "objective_comparable": true,
      "beta": [
        5.6656
      ],
      "coef_names": [
        "(Intercept)"
      ],
      "theta": [
        0
      ],
      "sigma": 3.6532,
      "is_singular": true
    },
    {
      "dataset": "dyestuff2",
      "formula": "Yield ~ 1 + (1 | Batch)",
      "family": "Gaussian",
      "link": "Identity",
      "estimator": "REML",
      "engine": "lme4",
      "status": "ok",
      "n_obs": 30,
      "objective": 161.8283,
      "objective_definition": "restricted_deviance",
      "objective_comparable": true,
      "beta": [
        5.6656
      ],
      "coef_names": [
        "(Intercept)"
      ],
      "theta": [
        0
      ],
      "sigma": 3.7157,
      "is_singular": true
    },
    {
      "dataset": "pastes",
      "formula": "strength ~ 1 + (1 | sample) + (1 | batch)",
      "family": "Gaussian",
      "link": "Identity",
      "estimator": "REML",
      "engine": "lme4",
      "status": "ok",
      "n_obs": 60,
      "objective": 246.9907,
      "objective_definition": "restricted_deviance",
      "objective_comparable": true,
      "beta": [
        60.0533
      ],
      "coef_names": [
        "(Intercept)"
      ],
      "theta": [
        3.5269,
        1.5635
      ],
      "sigma": 0.8234,
      "is_singular": false
    },
    {
      "dataset": "penicillin",
      "formula": "diameter ~ 1 + (1 | plate) + (1 | sample)",
      "family": "Gaussian",
      "link": "Identity",
      "estimator": "REML",
      "engine": "lme4",
      "status": "ok",
      "n_obs": 144,
      "objective": 330.8606,
      "objective_definition": "restricted_deviance",
      "objective_comparable": true,
      "beta": [
        22.9722
      ],
      "coef_names": [
        "(Intercept)"
      ],
      "theta": [
        1.5397,
        3.5125
      ],
      "sigma": 0.5499,
      "is_singular": false
    },
    {
      "dataset": "sleepstudy",
      "formula": "Reaction ~ 1 + Days + (1 + Days | Subject)",
      "family": "Gaussian",
      "link": "Identity",
      "estimator": "REML",
      "engine": "lme4",
      "status": "ok",
      "n_obs": 180,
      "objective": 1743.6283,
      "objective_definition": "restricted_deviance",
      "objective_comparable": true,
      "beta": [
        251.4051,
        10.4673
      ],
      "coef_names": [
        "(Intercept)",
        "Days"
      ],
      "theta": [
        0.9667,
        0.0152,
        0.2309
      ],
      "sigma": 25.5918,
      "is_singular": false
    },
    {
      "dataset": "sleepstudy",
      "formula": "Reaction ~ 1 + Days + (1 + Days | Subject)",
      "family": "Gaussian",
      "link": "Identity",
      "estimator": "ML",
      "engine": "lme4",
      "status": "ok",
      "n_obs": 180,
      "objective": 1751.9393,
      "objective_definition": "deviance",
      "objective_comparable": true,
      "beta": [
        251.4051,
        10.4673
      ],
      "coef_names": [
        "(Intercept)",
        "Days"
      ],
      "theta": [
        0.9292,
        0.0182,
        0.2226
      ],
      "sigma": 25.5919,
      "is_singular": false
    }
  ]
}
"""

